Реализована команда движения
OOAnD/Game pull request #37
Opened 2024-12-20 14:14 UTC by Angelina-Romanova2023

2024-12-20 14:15 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 90% | 16 | ✔
**Summary** | **100%** (46 / 46) | **90%** (9 / 10) | **16** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-20 14:23 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 100% | 15 | ✔
**Summary** | **100%** (46 / 46) | **100%** (8 / 8) | **15** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-23 14:01 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 67% | 13 | ✔
**Summary** | **100%** (41 / 41) | **67%** (4 / 6) | **13** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-23 14:07 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 100% | 13 | ✔
**Summary** | **100%** (41 / 41) | **100%** (6 / 6) | **13** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-23 14:18 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 100% | 13 | ✔
**Summary** | **100%** (41 / 41) | **100%** (6 / 6) | **13** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-23 19:17 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 83% | 13 | ✔
**Summary** | **100%** (41 / 41) | **83%** (5 / 6) | **13** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-23 19:37 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 100% | 13 | ✔
**Summary** | **100%** (41 / 41) | **100%** (6 / 6) | **13** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-25 15:31 UTC, osm1us requested changes
Стоит доработать и проверить остальное

2024-12-25 15:31 UTC, osm1us commented on SpaceBattle/MoveCommand.cs
Норм, но можно проще

2024-12-25 15:31 UTC, osm1us commented on SpaceBattle/RegisterIoCDependencyMoveCommand.cs
Норм (rotating?)

2024-12-25 15:31 UTC, osm1us commented on SpaceBattle/Vector.cs
Нет проверки на null

2024-12-25 15:31 UTC, osm1us commented on SpaceBattle.Tests/VectorTest.cs
Интересный тест для хэшкода)

2024-12-25 15:31 UTC, osm1us commented on SpaceBattle.Tests/RegisterDependencyMoveCommandTest.cs
1 мок не используется

2024-12-25 16:07 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 100% | 13 | ✔
**Summary** | **100%** (41 / 41) | **100%** (6 / 6) | **13** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-25 16:14 UTC, zaryanezrya requested changes

2024-12-25 16:14 UTC, zaryanezrya commented on SpaceBattle.Tests/VectorTest.cs
> +            vector1.GetHashCode();
В этом тесте нужно показать, что два вектора с одинаковыми координатами будут иметь одинаковый хэш-код

2024-12-25 16:44 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 100% | 13 | ✔
**Summary** | **100%** (41 / 41) | **100%** (6 / 6) | **13** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-25 16:52 UTC, ezyxip commented
![Code Coverage](https://img.shields.io/badge/Code%20Coverage-100%25-success?style=flat)

Package | Line Rate | Branch Rate | Complexity | Health
-------- | --------- | ----------- | ---------- | ------
SpaceBattle | 100% | 100% | 13 | ✔
**Summary** | **100%** (41 / 41) | **100%** (6 / 6) | **13** | ✔

<!-- Sticky Pull Request Comment -->

2024-12-25 21:03 UTC, zaryanezrya approved these changes

2025-06-02 18:19 UTC, merged